### PR TITLE
Removing RotoGrinders post from blog

### PR DESCRIPTION
**Pull request by louisemessage**

### CODE REVIEW

**Comment by engelgabriel** [comment]
Why are we removing RotoGrinders ?

**Comment by SeanPackham** [comment]
@engelgabriel let's discuss in our call.

**Comment by Sing-Li** [comment]
@o0lit3  we appreciate your help and contributions in our performance scaling session, and being interviewed by our PR representatives as a customer success story.

@SeanPackham  and team may reach out  shortly to write an improved version of the story for our new website content.

**Comment by SeanPackham** [comment]
Sing I will share our first version of our user persona's on Friday and we can discuss various posts you have pitched.

**Pull request merged**
