### PR TITLE
create webinars archive page

### PR DESCRIPTION
**Pull request by diegodorgam**
New PR with the modifications in webinars page, showing the recording archive.

captura de tela 2018-05-21 as 10 20 48

captura de tela 2018-05-21 as 10 21 13

captura de tela 2018-05-21 as 10 21 45

### CODE REVIEW

**Comment by diegodorgam** [comment]
Great idea!

Diego Dorgam
(61) 9 8183-0569

Em 22 de mai de 2018, à(s) 15:26, Gabriel Engel <notifications@github.com> escreveu:

**Comment by isabellarussell** [comment]
yes that could work, please go for it.

**Comment by engelgabriel** [comment]
@danilowoz can you work on this?

**Comment by danilowoz** [comment]
First of all, I think we should close this PR because these changes are very older than master branch. 

@isabellarussell 
- Which category should we use? Events or create another one? 
- How should the content look like? Can you propose content structure? (Such as content, date, link to the videos, got it? 
- Each last webinar should be a blog post? Or do you want to use a single post, with a list of last webinars?

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/rocketchat.github.io/issues/334

**Pull request closed without merging**
