### PR TITLE
[WIP] New English Webinar page

### PR DESCRIPTION
**Pull request by isabellarussell**
WIP do not merge, still needed:
- ICS calendar: updated entry
- new form to link to
- layout/format corrected 

@diegodorgam please help with the above. I thought it best to get started on my own but it is not ready yet.

### CODE REVIEW

**Comment by diegodorgam** [comment]
I think it's good to go @isabellarussell

**Comment by isabellarussell** [comment]
layout is great, thanks @diegodorgam !

The calendar entry doesn't work, not sure how to fix it:
image

**Comment by diegodorgam** [comment]
great, now we are good to go @isabellarussell

**Comment by isabellarussell** [comment]
great thank you!

little detail: is it normal that the phone dial code only offers the US dial code +1?
image

**Comment by diegodorgam** [comment]
Yes, I think so
captura de tela 2018-06-05 as 11 40 48

**Comment by isabellarussell** [comment]
Sorry, my comment wasn't clear. I meant, how come it doesn't offer any others dialling codes? Surely not all participants will be based in North America? 
People should be able to type in their own dial code no?

**Comment by diegodorgam** [comment]
oh yes sure, it's just a text hint, it's not a mask, you can erase it and type anything inside that field

**Comment by isabellarussell** [comment]
aah amazing! cool :)

**Pull request merged**
