### PR TITLE
Adding a message when there is no apps on a list

### LINKED ISSUE #416: Message component when a category is empty
Currently when user selects an empty category the list will be blank without any message. Some message like "no apps in this category yet" would be helpful!

### PR DESCRIPTION
**Pull request by rssilva**
Fix #416 

screen shot 2018-08-31 at 4 37 45 pm

### CODE REVIEW

**Comment by isabellarussell** [comment]
Agreed

**Comment by rssilva** [comment]
@engelgabriel @isabellarussell 

As we don't have any docs so far I'm removing empty categories before to render the list

screen shot 2018-09-03 at 11 12 15 am

**Comment by engelgabriel** [comment]
@rodrigok @graywolf336 do you think this is the best approach? To filter on the client level? Or should we have an API endpoint that returns ONLY categories with apps?

**Comment by rodrigok** [comment]
@engelgabriel If we want to filter the categories I'd say it should be server side, but IMHO keep the list there and show a message it's better while we don't have too much apps.

A link to the documentation page is necessary, I'll work on that this week after finish the webhook implementation (required to start the atlassian integrations).

**Comment by graywolf336** [comment]
I agree with @rodrigok here, that way people can see what options we will have in the future can options we can do. We need to do some developer evangelism to encourage people to start developing Apps and be vocal about it, that way people start creating Apps.

**Comment by geekgonecrazy** [comment]
Maybe if we had a docs page for getting started creating app could do:
> No apps in this category yet
> Developer?  Click here to get started creating an app

**Comment by engelgabriel** [comment]
Please take a look at https://apps.flock.com/ and let's implement 3 things.

1 - An illustration with "No result found" text.

image

2 - An option for people to request apps, maybe send them to the community forum?

image

3 - Developer? Click here to get started creating an app

**Comment by engelgabriel** [comment]
And please let not wait for the DOCs to implement this, just creat a placeholdes page on the docs if nesxcessary.

**Comment by rssilva** [comment]
- [ ] add icon

screen shot 2018-09-10 at 1 16 22 pm

**Comment by engelgabriel** [comment]
Let's merge this as it and make improvements on a new PR

**Pull request merged**
