### PR TITLE
[NEW] Add social links to footer

### PR DESCRIPTION
**Pull request by MartinSchoeler**
screen shot 2018-09-18 at 17 54 26
screen shot 2018-09-18 at 17 54 36

### CODE REVIEW

**Comment by isabellarussell** [comment]
Looking great @MartinSchoeler 🎉

**Comment by isabellarussell** [comment]
@MartinSchoeler @arthurgiustina see my comments on Abstract https://share.goabstract.com/2c9dec40-c847-4d26-8154-25a9c1429b83

**Comment by MartinSchoeler** [comment]
@isabellarussell @arthurgiustina @ggazzo Made changes based on the reviews
screen shot 2018-09-19 at 16 34 22
screen shot 2018-09-19 at 16 34 31

**Comment by isabellarussell** [comment]
@MartinSchoeler great! One tiny final change is to change the text to 'Star or Fork Us on GitHub'? so it matches the style of 'Connect with Us', thank you!

**Pull request merged**
