### PR TITLE
[NEW] Add sitemap and robots.txt to website

### PR DESCRIPTION
**Pull request by MartinSchoeler**
This should help with Indexing and help crawlers find more pages on our website.

If anyone has suggestions of what could be added to this file, please notify me!

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
Do we really want all of those doc pages and blog posts on the sitemap?  Especially static like that 😬

**Comment by isabellarussell** [comment]
I don't know enough about this to be able to provide any valuable advice! But thank you @MartinSchoeler for looking into it. Who else can we ask for insight?

**Comment by engelgabriel** [comment]
@MartinSchoeler are you automating the generations of the sitemap?

**Comment by engelgabriel** [comment]
https://help.github.com/articles/sitemaps-for-github-pages/

**Comment by MartinSchoeler** [comment]
@engelgabriel Alright, will try using the plugin, i did not know that this plugin was whitelisted by github pages. Closing this one

**Pull request closed without merging**
