### PR TITLE
Zapier announcement post

### PR DESCRIPTION
**Pull request by isabellarussell**

### CODE REVIEW

**Comment by isabellarussell** [comment]
@danilowoz could you fix the image used for the cover on the main blog page? It appears too zoomed in 
image

**Comment by danilowoz** [comment]
Hey @isabellarussell 
I actually used the background size as the cover, which means the image will fill the entire container, I think it's the best approach for this section. However, this image really didn't fit card well, so I suggest creating a new optional field like `imageHome` and choosing another image that fits well. 

Can I go ahead? I just need that you choose this new image.

**Comment by engelgabriel** [comment]
@isabellarussell is this ready to publish?

**Comment by isabellarussell** [comment]
@graywolf336 Have you had any feedback from Zapier Bradley? I really want to get this published.

@engelgabriel Bradley said he needed to check something with the Zapier guys.

**Pull request merged**
