### PR TITLE
Add 2nd webinar banner

### PR DESCRIPTION
**Pull request by isabellarussell**

### CODE REVIEW

**Comment by diegodorgam** [comment]
Great, hold this up a little @isabellarussell, I’ll send another form together, with a new presentation page, calendar and of course, an archive directory

**Comment by diegodorgam** [comment]
Now we're good to go, I'll add an archive pages later.

webinar2-ligero

**Comment by isabellarussell** [comment]
@diegodorgam this new page looks great, like the calendar too! Ready when you are :)

**Comment by diegodorgam** [comment]
Totally ready! All stuff automated, let's do this!

**Pull request merged**
