### PR TITLE
[FIX] Update team page

### LINKED ISSUE #459: Broken element on teams page
It looks like https://github.com/RocketChat/rocketchat.github.io/pull/453 was merged to soon 

captura de tela 2018-09-25 as 11 20 18

### PR DESCRIPTION
**Pull request by MartinSchoeler**
closes #459 
This fixes the broken about us element, and updates the team list.
Before:
image

After:
image

### CODE REVIEW

**Comment by marceloschmidt** [comment]
@MartinSchoeler @isabellarussell there's also duplicated text on the about us section.

2nd paragraph should be deleted:
```
We are building the future of communication and would love to build it with you. We are often looking for more team members, so check out our```

**Comment by marceloschmidt** [comment]
The link is also unformatted: ```https://rocketchat.recruitee.com Jobs page ```

**Comment by MartinSchoeler** [comment]
@marceloschmidt Fixed!

**Comment by marceloschmidt** [comment]
@MartinSchoeler did you fix the link too?

**Pull request merged**
