### PR TITLE
Android 2.6 release post

### PR DESCRIPTION
**Pull request by rafaelks**

### CODE REVIEW

**Comment by rafaelks** [comment]
@luciofm @filipedelimabrito @leonardoaramaki Guys, please help me adding information to this blog post? Need to add highlight information and also some detailed information about each one of them.

I was thinking about: custom emojis support, FOSS, admin panel... anything else?

**Comment by luciofm** [comment]
Rich messages

**Comment by filipedelimabrito** [comment]
Users tends to not considering it as a "feature" - they don't use that, but for us the analytics is very good.

What if we write something like: "Now you can enable Analytics tracking from the preferences to help us deliver a better software".  Something flashy that make users think we really want the best app ever.

**Comment by rafaelks** [comment]
screenshot_20180912-083032

screenshot_20180912-082925

screenshot_20180912-083004

**Comment by rafaelks** [comment]
@isabellarussell This one is ready to review! ✌️

**Pull request merged**
