### PR TITLE
Update Press page with latest articles

### PR DESCRIPTION
**Pull request by isabellarussell**
I wanted to add more recent press articles to the press page but have encountered a problem in doing so. 

Tested with adding one, but it has not worked and I can't figure out why... 🤔 
image

Had it worked, it should have appeared here:
image

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
@isabellarussell not sure why not working on yours but works on mine:
image

**Comment by isabellarussell** [comment]
oooh @geekgonecrazy that's so weird, my local preview might be wack...? gonna try again and see. Thanks for looking into this!

**Comment by MartinSchoeler** [comment]
@isabellarussell doing changes on `yml` files requires a server reset, you can do that simply shutting the process with  `CTRL+C`, if that fails you can delete the `_site` folder and restarting the server.

**Comment by geekgonecrazy** [comment]
Ah that's why!  Didn't even think of that.  Totally makes sense :)

**Comment by isabellarussell** [comment]
Yay, thanks @MartinSchoeler!
and @geekgonecrazy !

**Comment by MartinSchoeler** [comment]
@isabellarussell I think these new articles were already added https://rocket.chat/press should we close this?

**Pull request merged**
